language: node_js
branches:
  only:
    - master
notifications:
  email: 
    on_success: never
node_js:
  - '12'
script:
  - yarn test
  - yarn build
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
